### ISSUE TITLE
repeder is producing negative pedestal value

### ISSUE THREAD

**Issue by MyoungchulK** [ara-software/AraRoot#29]
It looks like median calculation is creating a negative value if there is no ADC distribution 
For example, A2 run 2319 is containing only a few events. So, when repeder is creating an ADC histogram for each sample index, some of the sample index's histogram has no counts at all.  
In this case, I believe median calculation is producing a negative value instead of 0 ADC
I suspect this is an integer conversion issue...

![image](https://user-images.githubusercontent.com/53809378/150940944-fbbc8c68-1d43-4576-b77a-deac3fabd41b.png)

**Comment by cozzyd** [comment]
That is strange... are you sure it's using a median and not a mean? The median should return the center of the histogram underflow bin in the case of no data, which of course isn't great but should also not produce what you're getting. If you send me the exact command you used to get this that is runnable on cobalt I can try to debug, although I'm on leave right now so it might take a while until I get to it :).

**Comment by MyoungchulK** [comment]
Hi Cosmin, I made this Ped. long time ago. But I think I used this command
`./repeder -d -m 0 -M 4096 /data/exp/ARA/2013/filtered/full2013Data/ARA02/root/run2319/event2319.root /path/to/output_path
`Let me also debug, too
