### ISSUE TITLE
Default A4, A5, and A6 voltage calibration files need to be replaced

### ISSUE THREAD

**Issue by clark2668** [ara-software/AraRoot#3]
As a stop-gap measure, we have copied the A3 voltage calibration files to be used for A4, A5, and A6. These need to be converted to real voltage calibration files when they become available.

**Comment by marcomuzio** [comment]
Completed with [PR#45](https://github.com/ara-software/AraRoot/pull/45) and [PR#18](https://github.com/ara-software/AraRoot/pull/18).
