### ISSUE TITLE
AraGeomTool is loading 2013-2017 SQL table for 2019~ data

### ISSUE THREAD

**Issue by MyoungchulK** [ara-software/AraRoot#36]
[if(unixtime==2018)](https://github.com/ara-software/AraRoot/blob/e618e7b8d346fa7877f712505782d08c0bed13ca/AraEvent/AraStationInfo.cxx#L49) need to be changed to` if(unixtime>=2018)`. So that 2019~ A1/3 data also can use new channel mapping

**Comment by clark2668** [comment]
@MyoungchulK , thanks for pushing this change! I am actually not so sure this was the intended usage? In particular, I think we _meant_ it to take _either_ the year _or_ the unixtime. The easy way to fix this might be to do something like

```
if(year < 3000){
   // check per year values
}
else{ 
   // check by unixtime
}

**Comment by MyoungchulK** [comment]
Thank you for the input. I made a pull request for further update;)
