### ISSUE TITLE
Default A4, A5 pedestal files need to be replaced

### ISSUE THREAD

**Issue by clark2668** [ara-software/AraRoot#4]
The pedestal subtraction files for A4 and A5 are for a single run. It's not clear if that's okay, or if we need to go to a annual average or something like that.

For A4, the file is pedestalValues.run006175.dat
For A5, the file is pedestalValues.run003961.dat

**Comment by marcomuzio** [comment]
Replaced with [PR#63](https://github.com/ara-software/AraRoot/issues/63).
